### ISSUE TITLE
search net arch error

### ISSUE THREAD

**Issue by githubgsq** [han-cai/PathLevel-EAS#12]
hi, @han-cai , I'm trying run "python3 arch_search.py --setting=pyramidnet-cell"
but it prompted that there's no model file.
![image](https://user-images.githubusercontent.com/23164715/47996062-3c3c4f80-e132-11e8-9304-2629c6ddfd10.png)

I trained a pyramid model with your run_pyramidnet.py, and copied the checkpoint.pth.tar as model.path, then put it in the directory above, but json can't decode it.
![image](https://user-images.githubusercontent.com/23164715/47996342-254a2d00-e133-11e8-8599-2c842981440a.png)

So, how the model.path should be generated?
Thanks.

**Comment by githubgsq** [comment]
hi, all, my question has been solved according to https://github.com/han-cai/PathLevel-EAS/issues/2.
Thanks a lot !

**Comment by alvinzhu123** [comment]
@githubgsq I have run run_pyramidnet.py to get net.config for almost 10s... When I put net.config in my folder_dir and begin to arch_search.py, I got the Error
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 25 (char 26)
There must be sth I got wrong. Could you tell me how to search arc with the codes? THX!
