### ISSUE TITLE
No model files in /...../placeholder/Arch_Search/DenseNet/placeholder/controller/model.path

### ISSUE THREAD

**Issue by jiachen0212** [han-cai/PathLevel-EAS#2]
Hello Mr Cai,  first of all, thanks very much for the codes...  Now  I want to do the same experiment, to search the architecture.  I use the command: 
python3 arch_search.py --setting=densenet-cell 
but i got the bug: 
No model files in /...../placeholder/Arch_Search/DenseNet/placeholder/controller/model.path
emmm...   maybe i use the code in a wrong way?  can you give some help?  thanks very much.....

**Comment by jiachen0212** [comment]
emmm... what's the meaning of file "model.pkl", maybe the bug is caused by it..  I modified the code to get the “model.path” and "model.pkl", but the "model.pkl" I got was invalid.

**Comment by han-cai** [comment]
By default, the code will check whether there is a model file in the given path. If yes, it will load that model file, otherwise, it will report "No model files in ..." which indicates the meta-controller is randomly initialized. So this is actually not a bug.

**Comment by jiachen0212** [comment]
@han-cai   thanks ver much...  finally I found that I used the wrong net.config file..... So the bug appeared....
emmm... Now I meet a new question....  maybe be the server_config ....
I write it as:
[
	["<client 1 address>", "<gpu_id_0>", "</...../PathLevel-EAS-master/code/CIFAR/client.py>"],
	["<client 2 address>", "<gpu_id_1>", "<...../PathLevel-EAS-master/code/CIFAR/client.py>"],
	["<client 3 address>", "<gpu_id_2>", "</..../Pytorch/PathLevel-EAS-master/code/CIFAR/client.py>"]
]
but it appears:
/bin/sh: 1: cannot open client: No such file
/bin/sh: 1: cannot open client: No such file
/bin/sh: 1: cannot open client: No such file
/bin/sh: 1: cannot open client: No such file
/bin/sh: 1: cannot open client: No such file
emmm.....  How can I rewrite the  server_config?  maybe I haven't understood what the file means....
